server:
  port: 8024
spring:
  application:
    name: users
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pfadb?createDatabaseIfNotExist=true&characterEncoding=UTF-8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
    username: marouane
    password: Marouane@2001
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: marouanedbibih.developer@gmail.com
    password: hxrcboubnwyekkly
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

