apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql-service
spec:
  selector:
    app: {{ .Release.Name }}-mysql
  ports:
      - protocol: TCP
        port: 3300
        targetPort: 3300
  type: ClusterIP