apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pfa-backend-service
spec:
  selector:
    app: {{ .Release.Name }}-pfa-backend
  ports:
      - protocol: TCP
        port: 8024
        targetPort: 8024
  type: LoadBalancer